### ISSUE TITLE
Add support for retry logic if ping fails or times out

### ISSUE THREAD

**Issue by cronitorio** [sm360/cronitor-client#5]
Hi @lboix,

I would like to start implementing retry logic in all of the Cronitor clients. In particular, we have an accute need to do this in the Java client first. If this is something you have time to help us with we would be grateful for your time. And, of course, we are happy to submit a PR for this as well if your time doesn't allow for it. :)

We would like our clients to be able to, by default, attempt to retry pings to Cronitor. The [CronitorCLI](https://cronitor.io/docs/using-cronitor-cli) attempts to make three requests to `cronitor.link` if those requests fail or time out, it then attempts the requests 3 times on `cronitor.io`.

Taking a quick peak through the library code I think the easiest place to implement the retry logic is within the [CronitorPinger](https://github.com/sm360/cronitor-client/blob/master/src/main/java/ca/sm360/cronitor/client/CronitorPinger.java). 

However, since that takes a fully built URL it may require lightly refactoring the internals of the methods in the [CronitorClient](https://github.com/sm360/cronitor-client/blob/master/src/main/java/ca/sm360/cronitor/client/CronitorClient.java). 

I've tried to psuedo-code what these changes could look like.

```java

// Within CronitorClient.java

public void run(String monitorCode) throws IOException, URISyntaxException {
    if(StringUtils.isNotBlank(monitorCode)) {
        // URL commandUrl = new RunCommandUrlGenerator().buildURI(monitorCode, apiKey);
        // cronitorPinger.ping(commandUrl);
        cronitorPinger.ping('run', monitorCode, apiKey);
    } else {
        logger.warning("We can't ping /run on cronitor because the monitor code is null or empty");
    }
}

public void complete(String monitorCode) throws IOException, URISyntaxException {
    if(StringUtils.isNotBlank(monitorCode)) {
       // URL commandUrl = new CompleteCommandUrlGenerator().withMessage(message).buildURI(monitorCode, apiKey);
         //  cronitorPinger.ping(commandUrl);
        cronitorPinger.ping('complete', monitorCode, apiKey);
    } else {
        logger.warning("We can't ping /complete on cronitor because the monitor code is null or empty");
    }
}



// Within CronitorPinger.java

public void ping(String command, String monitorCode, String apiKey) throws IOException, URISyntaxException {

    for (int i = 0; i < 5; i++) {
        private String subDomain = i < 3 ? ".link" : ".io"
        URL commandUrl = new CommandUrlGenerator(subDomain).buildURI(command, monitorCode, apiKey);
        logger.info("Will call url : " + commandURL);

        HttpURLConnection connection = (HttpURLConnection) commandURL.openConnection();
        connection.setConnectTimeout(cronitorPingTimeoutInSecond * 1000);

        try {
            connection.connect();
            connection.getInputStream();
            connection.disconnect();
            // not really sure how to do this in Java :)
            // retry on 5XX errors too
            if (connection.response().status() >= 500) {
                continue;
            }
        } catch (SocketTimeoutException ignore) {
            logger.warning(String.format("Failed to call url [%s] : a timeout occurred after %d seconds : [%s]",
                    commandURL, cronitorPingTimeoutInSecond, ignore));
            continue;
        }
        return;
    }
        
 }

```

**Comment by lboix** [comment]
Good idea @cronitorio ! Let me get back to you in this.

Regards

**Comment by lboix** [comment]
Moving to https://github.com/cronitorio/cronitor-java project now :)
